pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
	}
    stages {
      stage('Install Ansible') {
    steps {
        sh '''
        sudo apt-get update
        sudo apt-get install -y ansible
        '''
    }
}

        stage('Docker Login') {
            steps {
                // Add --password-stdin to run docker login command non-interactively
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Build & push Dockerfile') {
            steps {
                sh """
                cd Video-Personnalization-Frontend/
                ansible-playbook ansible-playbook.yml
                """
            }
        }
      
    } 
}
